#!/bin/bash  
 
curl -fsSL -o "/usr/local/hestia/install/common/templates/web/skel/document_errors/50x.html" "https://hestiamb.org/web/skel/document_errors/50x.html"
curl -fsSL -o "/usr/local/hestia/install/common/templates/web/skel/document_errors/403.html" "https://hestiamb.org/web/skel/document_errors/403.html" 
curl -fsSL -o "/usr/local/hestia/install/common/templates/web/skel/document_errors/404.html" "https://hestiamb.org/web/skel/document_errors/404.html"  
curl -fsSL -o "/usr/local/hestia/install/common/templates/web/skel/document_errors/410.html" "https://hestiamb.org/web/skel/document_errors/410.html"
curl -fsSL -o "/usr/local/hestia/install/common/templates/web/skel/public_html/index.html" "https://hestiamb.org/web/skel/public_html/index.html" 
curl -fsSL -o "/usr/local/hestia/install/common/templates/web/suspend/index.html" "https://hestiamb.org/web/suspend/index.html"
curl -fsSL -o "/usr/local/hestia/install/common/templates/web/unassigned/index.html" "https://hestiamb.org/web/unassigned/index.html"
curl -fsSL -o "/usr/local/hestia/data/templates/web/skel/public_html/index.html" "https://hestiamb.org/web/skel/public_html/index.html"
curl -fsSL -o "/usr/local/hestia/data/templates/web/skel/document_errors/403.html" "https://hestiamb.org/web/skel/document_errors/403.html"
curl -fsSL -o "/usr/local/hestia/data/templates/web/skel/document_errors/404.html" "https://hestiamb.org/web/skel/document_errors/404.html"
curl -fsSL -o "/usr/local/hestia/data/templates/web/skel/document_errors/410.html" "https://hestiamb.org/web/skel/document_errors/410.html"
curl -fsSL -o "/usr/local/hestia/data/templates/web/skel/document_errors/50x.html" "https://hestiamb.org/web/skel/document_errors/50x.html"
curl -fsSL -o "/usr/local/hestia/data/templates/web/suspend/index.html" "https://hestiamb.org/web/suspend/index.html"
curl -fsSL -o "/usr/local/hestia/data/templates/web/unassigned/index.html" "https://hestiamb.org/web/unassigned/index.html"
curl -fsSL -o "/usr/local/hestia/web/error/50x.html" "https://hestiamb.org/web/skel/document_errors/50x.html"
curl -fsSL -o "/usr/local/hestia/web/error/403.html" "https://hestiamb.org/web/skel/document_errors/403.html"
curl -fsSL -o "/usr/local/hestia/web/error/404.html" "https://hestiamb.org/web/skel/document_errors/404.html"
curl -fsSL -o "/usr/local/hestia/web/error/410.html" "https://hestiamb.org/web/skel/document_errors/410.html"
curl -fsSL -o "/usr/local/hestia/bin/v-add-sys-filemanager" "https://hestiamb.org/bin/v-add-sys-filemanager"
curl -fsSL -o "/usr/local/hestia/bin/v-list-sys-services" "https://hestiamb.org/bin/v-list-sys-services"
curl -fsSL -o "/usr/local/hestia/bin/v-update-web-domain-stat" "https://hestiamb.org/bin/v-update-web-domain-stat"
curl -fsSL -o "/usr/local/hestia/install/deb/templates/web/awstats/awstats.tpl" "https://hestiamb.org/awstats.tpl"
curl -fsSL -o "/usr/local/hestia/install/rpm/templates/web/awstats/awstats.tpl" "https://hestiamb.org/awstats.tpl"